version: 2
updates:
  # Librairies npm (Next.js)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Actions GitHub (workflows CI)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
